### ISSUE TITLE
Humble Games Collection doesn't launch

### ISSUE THREAD

**Issue by Zaleske** [Gustash/lutris_installers#8]
Hi, 

I've tried following your new instructions to get this working in Lutris on a Steam Deck, but I'm still getting the Javascript error. I'm fairly new to linux and Lutris so I'm puzzled.
Pardon the silly question, but I'm already lost at your first statement : "After allowing access to your account in the browser, if prompted for which application to handle `humble:` link in, you should select the `Humble Games Collection (Login)` application." 
Could you please elaborate? 
Thanks in advance

**Comment by Gustash** [comment]
That part would be after you've successfuly opened the app and are trying to login, which is after the point yours' is failing.

How did you install Humble? Did you simply search for it in Lutris and used the installer from there?

**Comment by Zaleske** [comment]
I think I did, yes. Not entirely sure though, it's been a while. Would you recommend another method?

**Comment by Gustash** [comment]
I would recommend trying to completely uninstall Humble Games Collection and reinstalling through the Lutris search functionality. It should install using the same installer that is in this repo.

Since you said it's been a while, and this installer has only been available for around a week or two, it seems like you'd used the previous installer which didn't work at all. There are some major changes on this one to make it work properly, so a clean install is recommended.

Let me know if that fixes you problem!

**Comment by Zaleske** [comment]
Thanks for your help. New installer indeed is a lot better, I managed to launch it and install a game, which launched fine under desktop mode, although controls didn't readily work (but that's expected). 
No luck launching Humble app in gaming mode so far though, but I'll keep fiddling to see if I can make it work.

**Comment by Gustash** [comment]
I've heard reports that sometimes it works, sometimes it does not. Seems to be a SteamOS issue as far as I can tell. I'll close this now since you've managed to get it working :)
